### ISSUE TITLE
Can you help with how to get started trying it out?

### ISSUE THREAD

**Issue by kevinrobinson** [CreativeInquiry/ImageCollectionSwiper#1]
Thanks for sharing, this seems cool! 😄 

I haven't used processing much, so was trying to try this out but didn't know how to do steps 1 and 2 in the instructions.  Is there a place I could read more about how to do that?  I tried looking at http://processingjs.org/articles/jsQuickStart.html but wasn't sure what to do.  Thanks for your help 👍

**Comment by golanlevin** [comment]
This project uses Processing (Java), not the JavaScript variant ProcessingJS (which anyway has been superseded in the past few years by p5.js). You can get started at http://processing.org. Explaining the basics of how to use Processing is way outside the scope of any support we can provide; we recommend you spend time with Dan Shiffman's "Coding Train" channel on YouTube https://www.youtube.com/channel/UCvjgXvBlbQiydffZU7m1_aw, especially including his playlist for Learning Processing.

**Comment by kevinrobinson** [comment]
Ah thanks, knowing that it uses Java processing is helpful :)

FWIW, trying it out on OSX I get a NullPointerException which looks like it might be from differences in working with filesystem paths across OSes:

![image](https://user-images.githubusercontent.com/1056957/61975782-0ee14b80-afb8-11e9-9315-94df1b2bb60b.png)

I'll move on, but figured I'd share and thanks for your help!
